language: swift
xcode_workspace: Rocky.xcworkspace
xcode_scheme: Rocky
osx_image: xcode10
cache: 
  - bundler
  - cocoapods
before_install:
  - pod repo update
install:
  - bundle install 
  - pod install
script:
  - set -o pipefail
  - xcodebuild -workspace Rocky.xcworkspace -scheme Rocky -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build test | xcpretty --test --color
  - bundle exec danger
